spring:
    profiles:
        active: 'prod'
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true     
                use_sql_comments: true 
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
server:
  port: 8081

appointment:
    app:
        jwtSecret: "wSQbwfMLEimcIDjJzRetzWhDpbpuXqkxcHaqVEWD"
        jwtExpirationMs: 86400000