spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: appointment
    datasource:
        url: ${DATABASE_URL_PROD}
        username: ${PROD_USERNAME}
        password: ${PROD_PASSWORD}