spring:
    application:
        name: appointment2206082985
    datasource:
        url: jdbc:postgresql://localhost:15001/appointment2206082985
        username: postgres
        password: secret99
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
